# Site settings
title: HMI Lab
email: hxy_harold@163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
weibo:    2634871552
github:   Maxhead
# codepen:  username
# dribbble: username

# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
# favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico
favicon: https://raw.githubusercontent.com/Maxhead/Maxhead.github.io/master/assets/icon/favicon.ico


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown

kramdown:
  input: GFM
sass:
  style: compressed
gems:
  - jekyll-sitemap
port: 5001
